---
## This playbook deploys the whole application stack

# display ansible information
- hosts: all
  strategy: debug
  tasks:
    - name: show all ansible system variables
      debug: var=ansible_facts
      tags:
        - never
        - debug
    - name: display summary
      debug:
        msg: "{{ item }}"
      with_items:
        - "ansible_all_ipv4_addresses: {{ ansible_all_ipv4_addresses }}"
        - "ansible_distribution: {{ ansible_distribution }}"
        - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
        - "ansible_hostname: {{ ansible_hostname }}"
        - "ansible_date_time.date: {{ ansible_date_time.date }}"
        - "ansible_python_version: {{ ansible_python_version }}"
        - "ansible_user_dir: {{ ansible_user_dir }}"
      tags:
        - debug

# mac specific tasks
- include: mac.yml
  when:
    - ansible_distribution == "MacOSX"
